---
- hosts: test-servers
  sudo: yes
  vars:
    users:
      - { name: "", pass: "", key: ""}
  tasks:
  - name: create {{ item.name }} user
    user: name={{ item.name }} comment="{{ item.name }} Created." group=luxon password={{ item.pass }} createhome=yes state=present
    with_items: users
  - name: directory
    file: path=/home/{{ item.name }}/.ssh state=directory owner={{ item.name }} group=users mode=700
    with_items: users
  - name: authorized_keys
    authorized_key: user={{ item.name }} key="{{ item.key }}"
    with_items: users

# create password oneliner. please paste users.pass.
# python -c 'import crypt; print crypt.crypt("hogehoge", "$1$SomeSalt$")'

