- name: exist perlbrew
  stat: path=~/perl5/perlbrew/bin/perlbrew
  register: exist_perlbrew
  sudo_user: "{{ exec_user }}"

- name: install perlbrew
  when: exist_perlbrew.stat.md5 is not defined
  action: shell curl -L http://install.perlbrew.pl | bash
  sudo_user: "{{ exec_user }}"

- name: exist perlbrew setting
  shell: grep '[[ -s "$HOME/perl5/perlbrew/etc/bashrc" ]] && source "$HOME/perl5/perlbrew/etc/bashrc"' $HOME/.bashrc | wc -l
  sudo_user: "{{ exec_user }}"
  register: exist_perlbrew_setting

- name: bashrc for perlbrew
  when: exist_perlbrew_setting.stdout == "0"
  action: shell echo '[[ -s "$HOME/perl5/perlbrew/etc/bashrc" ]] && source "$HOME/perl5/perlbrew/etc/bashrc"' >> $HOME/.bashrc
  sudo_user: "{{ exec_user }}"

- name: install perl {{ version }}
  shell: "{{ perlbrew_dir }}/perlbrew install perl-{{ version }} 2>&1"
  register: res
  ignore_errors: True
  sudo_user: "{{ exec_user }}"
- debug: msg="{{res}}"

- name: switch perl version {{ version }}
  shell: "{{ perlbrew_dir }}/perlbrew switch perl-{{ version }}"
  when: res.stdout.find('installed') != -1
  sudo_user: "{{ exec_user }}"

- name: isntall cpanm
  action: shell {{ perlbrew_dir }}/perlbrew install-cpanm creates={{ perlbrew_dir }}/cpanm
  sudo_user: "{{ exec_user }}"
