- name: check exist binfile
  stat: path={{ src }}/{{ version }}/bin/kibana
  register: binfile

- name: get tar.gz
  when: binfile.stat.md5 is not defined
  get_url: url={{ tar_gz }} dest={{ src }}

- name: decompress tar.gz
  when: binfile.stat.md5 is not defined
  command: tar xvzf {{ version }}.tar.gz --remove-files  chdir={{ src }}

- name: set kibana config
  replace: dest={{ src }}/{{ version }}/config/kibana.yml regexp='http://.*:9200' replace="http://{{ kibana_elasticsearch_ip }}:9200" backup=yes
  register: config_replace
  notify: reload supervisor

- name: set supervisor config
  ini_file: dest=/etc/supervisord.conf
            section=program:{{ kibana_supervisor_program_name }}
            option={{ item.option }}
            value={{ item.value }}
  with_items:
    - option: command
      value: "{{ src }}/{{ version }}/bin/kibana"
    - option: autostart
      value: true
    - option: autorestart
      value: true
    - option: stopsignal
      value: QUIT
    - option: log_stdout
      value: true
    - option: log_stderr
      value: true
    - option: logfile
      value: /var/log/supervisor/kibana.log
  notify: reload supervisor

