- name: install
  yum: name=supervisor state=installed enablerepo=epel

- name: check exist config
  stat: path=/etc/supervisord.conf
  register: file

- name: echo config file
  when: file.stat.md5 is not defined
  shell: "echo_supervisord_conf > /etc/supervisord.conf"

- name: run
  service: name=supervisord state=running

