---
- name: check installed java
  shell: which java
  register: java_is_installed
  ignore_errors: yes
  changed_when: false

- name: Download Oracle jdk
  when: java_is_installed.rc == 1
  shell: "curl -L  -H 'Cookie:oraclelicense=accept-securebackup-cookie' -o {{ src_dir }}/{{ oracle_java.rpm.filename }} {{ oracle_java.rpm.url }}"

- name: install RPM
  when: java_is_installed.rc == 1
  shell: rpm  -ivh {{ src_dir }}/{{ oracle_java.rpm.filename }}

- name: set Java version as default
  when: java_is_installed.rc == 1
  shell: alternatives --set java {{ oracle_java.home }}/jre/bin/java
