- name: set repository
  copy: src=repo.ini dest=/etc/yum.repos.d/pandramfs.repo

- name: install pandorafms
  yum: name={{ item }} state=installed enablerepo=epel
  with_items:
    # - makecache
    - httpd
    - perl-Encode-Locale
    - pandorafms_console
    - pandorafms_server

- name: httpd start
  service: name=httpd state=running

