- name: create directory
  file: path={{ sampleapp_directory }} state=directory owner={{ sampleapp_user }} mode=0755

- name: set app
  template: src=app.j2 dest={{ sampleapp_directory }}/app.psgi owner={{ sampleapp_user }} mode=644

- name: set run
  template: src=run.j2 dest={{ sampleapp_directory }}/run owner={{ sampleapp_user }} mode=755

- name: set env
  template: src=env.j2 dest={{ sampleapp_directory }}/env owner={{ sampleapp_user }} mode=755

- name: exist perl modules
  shell: perl -M{{ item }} -e 'print ${{ item }}::VERSION'
  ignore_errors: True
  register: exist_perlmodule
  sudo_user: "{{ sampleapp_user }}"
  with_items: perlmodules

- name: install perlmodule
  when: item.1.stderr.find('locate') == 6
  shell: "{{ home_dir }}/perl5/perlbrew/bin/cpanm {{ item.0 }}"
  sudo_user: "{{ sampleapp_user }}"
  with_together:
    - perlmodules
    - exist_perlmodule.results

- name: set supervisor config
  ini_file: dest=/etc/supervisord.conf
            section=program:"{{ item.program }}"
            option="{{ item.option }}"
            value="{{ item.value }}"
  with_items: supervisor_config
  notify: reload supervisor



