- name: create directory
  file: path={{ sampleapp_directory }} state=directory owner={{ sampleapp_user }} mode=0755

- name: set app
  template: src=app.j2 dest={{ sampleapp_directory }}/app.psgi owner={{ sampleapp_user }} mode=644

- name: set run
  template: src=run.j2 dest={{ sampleapp_directory }}/run owner={{ sampleapp_user }} mode=755

- name: set env
  template: src=env.j2 dest={{ sampleapp_directory }}/env owner={{ sampleapp_user }} mode=755

- name: exist module Server::Starter
  shell: perl -MServer::Starter -e 'print $Server::Starter::VERSION'
  ignore_errors: True
  register: exist_server_starter
  sudo_user: "{{ sampleapp_user }}"

- name: install Server::Starter
  when: exist_server_starter.stderr.find('locate') == 6
  shell: "{{ home_dir }}/perl5/perlbrew/bin/cpanm Server::Starter"
  sudo_user: "{{ sampleapp_user }}"

- name: exist module Net::Server::SS::PreFork
  shell: perl -MNet::Server::SS::PreFork -e 'print $Net::Server::SS::PreFork::VERSION'
  ignore_errors: True
  register: exist_net_server_ss_prefork
  sudo_user: "{{ sampleapp_user }}"

- name: debug
  debug: var=exist_net_server_ss_prefork.stderr.find('locate')

- name: install Net::Server::SS::Prefork
  when: exist_net_server_ss_prefork.stderr.find('locate') == 6
  shell: "{{ home_dir }}/perl5/perlbrew/bin/cpanm Net::Server::SS::PreFork"
  sudo_user: "{{ sampleapp_user }}"

- name: set supervisor config
  ini_file: dest=/etc/supervisord.conf
            section=program:"{{ item.program }}"
            option="{{ item.option }}"
            value="{{ item.value }}"
  with_items: supervisor_config
  notify: reload supervisor



