app_user: vagrant
perl_build:
  url: https://github.com/tokuhirom/Perl-Build.git
  path: ~/.plenv/plugins/perl-build

plenv_local: 5.18.2

plenv:
  bin: ~/.plenv/bin/plenv
  url: https://github.com/tokuhirom/plenv.git
  user: "{{ app_user | default('vagrant') }}"
  local: "{{ plenv_local }}"
  global: "{{ plenv_global | default(plenv_local)}}"

