app_user: sawafuji.yuya
plenv:
  shell: ~/.bashrc
  user: "{{ app_user | default('vagrant') }}"
  envs:
    - 'export PATH="$HOME/.plenv/bin:$PATH"'
    - 'eval "$(plenv init -)"'

  version:
  global: 5.18.2
